mod pbuilderrc to use ubuntu or debian repos

diff --git a/pbuilderrc b/pbuilderrc
--- a/pbuilderrc
+++ b/pbuilderrc
@@ -48,26 +48,48 @@ fi
 # (e.g., sudo DIST=xenial ARCH=arm64 pbuilder --update --override-config)
 
 # IMPORTANT DEBUGGING NOTE: If you are getting broken packages from apt
-# try logging into the chroot with sudo DIST=xenial ARCH=(whatever arch) pbuilder --login
-# Run apt-cache policy (package-name-here)
-# compare with apt-cache policy (package-name-here) outside of chroot
+# try logging into the chroot with sudo DIST=<dist> ARCH=<arch> pbuilder --login
+# Run apt-cache policy <package-name>
+# compare with apt-cache policy <package-name> outside of chroot
 # If they are different, add the missing components to OTHERMIRROR
-if [ "${ARCH}" == "armhf" ] || [ "${ARCH}" == "arm64" ]; then
-   MIRRORSITE="http://ports.ubuntu.com/ubuntu-ports/"
-   COMPONENTS="main restricted universe multiverse"
-   OTHERMIRROR="deb http://ports.ubuntu.com/ubuntu-ports/ ${DIST} main restricted universe multiverse
-   |deb http://ports.ubuntu.com/ubuntu-ports/ ${DIST}-updates main universe multiverse
-   |deb [trusted=yes] http://repos.rcn-ee.com/ubuntu/ ${DIST} main
-   |deb [trusted=yes] http://ppa.launchpad.net/kevin-demarco/scrimmage/ubuntu ${DIST} main
-   |deb [trusted=yes] http://packages.ros.org/ros/ubuntu ${DIST} main"
 
-elif [ "${ARCH}" == "amd64" ] || [ "${ARCH}" == "i386" ]; then
-   MIRRORSITE="http://us.archive.ubuntu.com/ubuntu/"
-   COMPONENTS="main restricted universe multiverse"
+# Determine the OS being used based on the distribution name
+if [ "${DIST}" == "trusty" ] || [ "${DIST}" == "xenial" ] || [ "${DIST}" == "bionic" ]; then
+    OS="Ubuntu"
+elif [ "${DIST}" == "buster" ] || [ "${DIST}" == "jessie" ] || [ "${DIST}" == "stretch" ]; then
+    OS="Debian"
+else
+    echo "Invalid distribution: ${DIST}"
+    OS="INVALID"
+    exit 1
+fi
 
-   OTHERMIRROR="deb [trusted=yes] http://ppa.launchpad.net/kevin-demarco/scrimmage/ubuntu ${DIST} main
-   |deb http://us.archive.ubuntu.com/ubuntu/ ${DIST}-updates main universe multiverse
-   |deb [trusted=yes] http://packages.ros.org/ros/ubuntu ${DIST} main"
+# Set the mirror based on the OS
+if [ "$OS" == "Debian" ]; then
+    MIRRORSITE="http://ftp.debian.org/debian/"
+    COMPONENTS="main contrib non-free"
+    DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}"
+                     "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg")
+elif [ "$OS" == "Ubuntu" ]; then
+    # Ubuntu has different servers for arm and x86
+    if [ "${ARCH}" == "armhf" ] || [ "${ARCH}" == "arm64" ]; then
+        MIRRORSITE="http://ports.ubuntu.com/ubuntu-ports/"
+        COMPONENTS="main restricted universe multiverse"
+        OTHERMIRROR="deb http://ports.ubuntu.com/ubuntu-ports/ ${DIST} main restricted universe multiverse
+                    |deb http://ports.ubuntu.com/ubuntu-ports/ ${DIST}-updates main universe multiverse
+                    |deb [trusted=yes] http://repos.rcn-ee.com/ubuntu/ ${DIST} main
+                    |deb [trusted=yes] http://ppa.launchpad.net/kevin-demarco/scrimmage/ubuntu ${DIST} main
+                    |deb [trusted=yes] http://packages.ros.org/ros/ubuntu ${DIST} main"
+    else
+        MIRRORSITE="http://us.archive.ubuntu.com/ubuntu/"
+        COMPONENTS="main restricted universe multiverse"
+
+        OTHERMIRROR="deb [trusted=yes] http://ppa.launchpad.net/kevin-demarco/scrimmage/ubuntu ${DIST} main
+                    |deb http://us.archive.ubuntu.com/ubuntu/ ${DIST}-updates main universe multiverse
+                    |deb [trusted=yes] http://packages.ros.org/ros/ubuntu ${DIST} main"
+    fi
+else
+    echo "Invalid OS: ${OS}"
 fi
 
 if [ "$ARCH" == "armhf" ] && [ "$(dpkg --print-architecture)" != "armhf" ]; then
